# Generated by Django 4.0.2 on 2022-05-12 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(default='user', max_length=255)),
                ('username', models.CharField(default='', max_length=255, unique=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('deviceId', models.CharField(default='', max_length=255)),
                ('hits', models.IntegerField()),
                ('misses', models.IntegerField()),
                ('avgHitSpeed', models.FloatField(max_length=255)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('version', models.CharField(max_length=255)),
                ('gameType', models.CharField(max_length=255)),
                ('targetHitSpeedList', models.JSONField(default=dict)),
                ('leftArmSpeedList', models.JSONField(default=dict)),
                ('rightArmSpeedList', models.JSONField(default=dict)),
                ('headSpeedList', models.JSONField(default=dict)),
                ('leftArmAvgSpeed', models.FloatField(max_length=32, null=True)),
                ('rightArmAvgSpeed', models.FloatField(max_length=32, null=True)),
                ('headAvgSpeed', models.FloatField(max_length=32, null=True)),
                ('leftArmSpaceCoverage', models.JSONField(default=dict)),
                ('rightArmSpaceCoverage', models.JSONField(default=dict)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='server.user')),
            ],
        ),
    ]
